### ISSUE TITLE
"Relation App_filemodel does not exist" error when uploading or deleting files

### ISSUE THREAD

**Issue by marcogdepinto** [marcogdepinto/Deep-learning-model-deploy-with-django#9]
`Request Method: | GET
https://emotion-classification-ravdess.herokuapp.com/filedelete/
ProgrammingError
relation "App_filemodel" does not exist LINE 1: SELECT "App_filemodel"."id" FROM "App_filemodel" WHERE "App_... `

**Comment by marcogdepinto** [comment]
Workaround: using version 1.1.

**Comment by alezenonos** [comment]
Amazing Work! What is is the workaround? What date shall we checkout?

**Comment by marcogdepinto** [comment]
@alezenonos hi, try version 1.1, source code here - https://github.com/marcogdepinto/Deep-learning-model-deploy-with-django/releases/tag/v.1.1 . If it's not working let me know. Unfortunately I have no bandwidth to debug in the short term.

**Comment by alezenonos** [comment]
Thanks for your reply. 

Actually it worked for some reason. I just tried the followings again:
python manage.py makemigrations App
python manage.py migrate App

Also (for everyone else landed on this), had to change the user and create the db of course.

**Comment by marcogdepinto** [comment]
@alezenonos the issue was actually the one you described. Thanks for the hint, the migrations solved the issue. I also used this opportunity to refresh the requirements.txt to bump the Django version to Django 3 and adjust the other correct dependencies, will close this and release a new version soon. Thank you again!
